import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { BookOpen, BookmarkPlus, Captions, ChevronLeft, ChevronRight, CircleHelp, Download, Eye, EyeOff, FileAudio, GraduationCap, Headphones, LocateFixed, Mic2, MoreHorizontal, Pause, Play, Plus, Repeat2, RotateCcw, Scissors, Settings2, Sparkles, Upload, Volume2, VolumeX, Waves, X } from 'lucide-react'
import LibraryPanel from './LibraryPanel'
import { deleteProject, getLatestProject, getProject, listProjects, projectIdFor, saveProject, type ProjectSummary, type StoredProject } from './storage'
import { exportCoursePackage } from './coursePackage'

type Segment={id:number;start:number;end:number}; type Cue={id:number;start:number;end:number;text:string;edited?:boolean}; type SavedRecord={id:number;fileName:string;start:number;end:number;text:string;created:string}; type Dialog='help'|'settings'|'history'|'range'|'import'|null
const fmt=(s:number,p=false)=>{const v=Number.isFinite(s)?Math.max(0,s):0;return `${Math.floor(v/60)}:${p?(v%60).toFixed(1).padStart(4,'0'):Math.floor(v%60).toString().padStart(2,'0')}`}
const isDesktopRuntime=window.location.protocol==='tauri:'||window.location.hostname==='tauri.localhost'
const API_BASE=isDesktopRuntime?'http://127.0.0.1:8000':'/api'
const isAudioMedia=(name:string,type:string)=>type.startsWith('audio/')||(!type.startsWith('video/')&&/\.(mp3|wav|m4a|aac|flac|ogg|opus|wma)$/i.test(name))

function detectSegments(buffer:AudioBuffer):Segment[]{
  const data=buffer.getChannelData(0), frameSec=.04, size=Math.max(1,Math.floor(buffer.sampleRate*frameSec)), energy:number[]=[]
  for(let o=0;o<data.length;o+=size){let sum=0,n=0;for(let i=o;i<Math.min(data.length,o+size);i+=4){sum+=data[i]*data[i];n++}energy.push(Math.sqrt(sum/Math.max(1,n)))}
  const sorted=[...energy].sort((a,b)=>a-b), high=sorted[Math.floor(sorted.length*.9)]||.01, threshold=Math.max(.003,Math.min(.03,high*.12)), cuts=[0];let silence=-1
  for(let i=0;i<energy.length;i++){if(energy[i]<threshold){if(silence<0)silence=i}else if(silence>=0){if(i-silence>=Math.ceil(.48/frameSec))cuts.push((silence+i)/2*frameSec);silence=-1}}
  cuts.push(buffer.duration);const clean=[...new Set(cuts.map(v=>+Math.max(0,Math.min(buffer.duration,v)).toFixed(2)))].sort((a,b)=>a-b), ranges:Array<[number,number]>=[]
  for(let i=0;i<clean.length-1;i++){let start=clean[i],end=clean[i+1];while(end-start>16){ranges.push([start,start+12]);start+=12}if(end-start>=1||!ranges.length)ranges.push([start,end]);else ranges[ranges.length-1][1]=end}
  return ranges.map(([start,end],i)=>({id:i+1,start,end}))
}
function createWaveform(buffer:AudioBuffer,count=360){const data=buffer.getChannelData(0),block=Math.max(1,Math.floor(data.length/count)),out:number[]=[];for(let i=0;i<count;i++){let peak=0;for(let j=i*block;j<Math.min(data.length,(i+1)*block);j+=Math.max(1,Math.floor(block/80)))peak=Math.max(peak,Math.abs(data[j]));out.push(peak)}const max=Math.max(...out,.01);return out.map(v=>Math.max(3,v/max*58))}
function encodeWavClip(buffer:AudioBuffer,start:number,end:number){const from=Math.floor(start*buffer.sampleRate),to=Math.min(buffer.length,Math.ceil(end*buffer.sampleRate)),frames=Math.max(1,to-from),bytes=new ArrayBuffer(44+frames*2),view=new DataView(bytes);const write=(at:number,value:string)=>{for(let i=0;i<value.length;i++)view.setUint8(at+i,value.charCodeAt(i))};write(0,'RIFF');view.setUint32(4,36+frames*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,frames*2,true);const channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),step=Math.max(1,Math.floor(frames/20000)),energy=channels.map(channel=>{let sum=0;for(let i=from;i<to;i+=step){const value=channel[i]||0;sum+=value*value}return sum}),channel=channels[energy.indexOf(Math.max(...energy))]||channels[0];for(let i=0;i<frames;i++){const sample=Math.max(-1,Math.min(1,channel[from+i]||0));view.setInt16(44+i*2,sample<0?sample*0x8000:sample*0x7fff,true)}return new Blob([bytes],{type:'audio/wav'})}
const stamp=(value:string)=>{const parts=value.trim().replace(',','.').split(':').map(Number);return parts.length===3?parts[0]*3600+parts[1]*60+parts[2]:parts[0]*60+parts[1]}
function parseSubtitles(source:string):Cue[]{const blocks=source.replace(/\r/g,'').trim().split(/\n\s*\n/),out:Cue[]=[];for(const block of blocks){const lines=block.split('\n'),timeIndex=lines.findIndex(line=>line.includes('-->'));if(timeIndex<0)continue;const [a,b]=lines[timeIndex].split('-->').map(v=>v.trim().split(/\s+/)[0]);const text=lines.slice(timeIndex+1).join(' ').replace(/<[^>]+>/g,'').trim();if(text)out.push({id:out.length+1,start:stamp(a),end:stamp(b),text})}return out}

export default function App(){
  const mediaRef=useRef<HTMLVideoElement>(null),fileRef=useRef<HTMLInputElement>(null),subtitleRef=useRef<HTMLInputElement>(null),mediaFileRef=useRef<File|null>(null),audioBufferRef=useRef<AudioBuffer|null>(null),recorderRef=useRef<MediaRecorder|null>(null),currentSegmentRef=useRef<HTMLButtonElement>(null)
  const [mediaUrl,setMediaUrl]=useState(''),[fileName,setFileName]=useState('未导入媒体'),[duration,setDuration]=useState(0),[waveform,setWaveform]=useState<number[]>([]),[segments,setSegments]=useState<Segment[]>([]),[selectedIds,setSelectedIds]=useState<number[]>([]),[range,setRange]=useState<[number,number]>([0,1]),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[looping,setLooping]=useState(false),[speed,setSpeed]=useState(1),[muted,setMuted]=useState(false),[processing,setProcessing]=useState(false),[dialog,setDialog]=useState<Dialog>(null),[toast,setToast]=useState(''),[mode,setMode]=useState<'listening'|'shadowing'>('listening'),[recording,setRecording]=useState(false),[recordingUrl,setRecordingUrl]=useState('')
  const [mediaIsAudio,setMediaIsAudio]=useState(false)
  const [sourceUrl,setSourceUrl]=useState(''),[urlLoading,setUrlLoading]=useState(false)
  const [processingMessage,setProcessingMessage]=useState('正在本地提取音轨、计算真实波形…')
  const [cues,setCues]=useState<Cue[]>([]),[draftText,setDraftText]=useState(''),[records,setRecords]=useState<SavedRecord[]>(()=>{try{return JSON.parse(localStorage.getItem('echo-loop-records')||'[]')}catch{return[]}})
  const localModel:'small'='small',[splitMode,setSplitMode]=useState<'silence'|'whisperx'|'nvidia'>('silence'),[transcribing,setTranscribing]=useState(false),[detectedLanguage,setDetectedLanguage]=useState('')
  const [cloudLanguage,setCloudLanguage]=useState('ja-JP')
  const [projectId,setProjectId]=useState(''),[restoring,setRestoring]=useState(true)
  const [libraryOpen,setLibraryOpen]=useState(false),[projects,setProjects]=useState<ProjectSummary[]>([]),[saveStatus,setSaveStatus]=useState<'idle'|'saving'|'saved'|'error'>('idle')
  const [showTranscript,setShowTranscript]=useState(true)
  const [showLiveCaption,setShowLiveCaption]=useState(false)
  const [exporting,setExporting]=useState(false)
  const [subtitleActionsTarget,setSubtitleActionsTarget]=useState<Element|null>(null)
  const [segmentToolsTarget,setSegmentToolsTarget]=useState<Element|null>(null)
  const [captionTarget,setCaptionTarget]=useState<Element|null>(null)
  const [mediaStageTarget,setMediaStageTarget]=useState<Element|null>(null)
  const currentIndex=useMemo(()=>segments.findIndex(s=>s.id===selectedIds[0]),[segments,selectedIds])
  const playingIndex=useMemo(()=>{
    if(!segments.length)return -1
    const exact=segments.findIndex(s=>time>=s.start&&time<s.end)
    if(exact>=0)return exact
    return segments.reduce((best,s,index)=>Math.abs(s.start-time)<Math.abs(segments[best].start-time)?index:best,0)
  },[segments,time])
  const visibleWindow=useMemo(()=>{
    const count=Math.min(20,segments.length), center=playingIndex>=0?playingIndex:Math.max(0,currentIndex)
    let start=Math.max(0,center-Math.floor(count/2));start=Math.min(start,Math.max(0,segments.length-count))
    return {start,end:start+count,items:segments.slice(start,start+count)}
  },[segments,playingIndex,currentIndex])
  const selectedRange=useMemo<[number,number]|null>(()=>{const picked=segments.filter(s=>selectedIds.includes(s.id)).sort((a,b)=>a.start-b.start);return picked.length?[picked[0].start,picked[picked.length-1].end]:null},[segments,selectedIds])
  const cueStart=selectedRange?.[0]??range[0],cueEnd=selectedRange?.[1]??range[1]
  const visibleCues=useMemo(()=>cues.filter(cue=>cue.end>cueStart&&cue.start<cueEnd),[cues,cueStart,cueEnd])
  const activeCue=useMemo(()=>cues.find(cue=>time>=cue.start&&time<cue.end)??null,[cues,time])
  useEffect(()=>{if(mediaRef.current)mediaRef.current.playbackRate=speed},[speed]);useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(id)},[toast])
  useEffect(()=>{document.body.classList.toggle('transcript-hidden',!showTranscript);return()=>document.body.classList.remove('transcript-hidden')},[showTranscript])
  useEffect(()=>{setSubtitleActionsTarget(document.querySelector('.subtitle-head'))},[mode,mediaUrl])
  useEffect(()=>{setSegmentToolsTarget(document.querySelector('.segment-tools'))},[mediaUrl,segments.length])
  useEffect(()=>{setCaptionTarget(document.querySelector('.media-card'))},[mediaUrl])
  useEffect(()=>{setMediaStageTarget(document.querySelector('.media-stage'))},[mediaUrl])
  useEffect(()=>{void (async()=>{try{setProjects(await listProjects());const saved=await getLatestProject();if(!saved)return;await restoreProject(saved);setToast('已自动恢复上次学习项目')}catch{setToast('上次项目恢复失败，可从学习库重新打开')}finally{setRestoring(false)}})()},[])
  useEffect(()=>{const file=mediaFileRef.current;if(!mediaUrl||!file)return;setProjectId(projectIdFor(file))},[mediaUrl])
  useEffect(()=>{if(!projectId||processing||restoring||!mediaFileRef.current||!duration)return;setSaveStatus('saving');const timer=setTimeout(()=>{const file=mediaFileRef.current;if(!file)return;void saveProject({id:projectId,fileName:file.name,fileType:file.type,lastModified:file.lastModified,media:file,duration,waveform,segments,cues,selectedIds,range,detectedLanguage,updatedAt:Date.now()}).then(async()=>{setSaveStatus('saved');setProjects(await listProjects())}).catch(()=>{setSaveStatus('error');setToast('本地空间不足，项目自动保存失败')})},700);return()=>clearTimeout(timer)},[projectId,processing,restoring,duration,waveform,segments,cues,selectedIds,range,detectedLanguage])
  useEffect(()=>{const item=currentSegmentRef.current,container=item?.parentElement;if(!container||!item)return;container.scrollTo({top:Math.max(0,item.offsetTop-container.offsetTop-container.clientHeight/2+item.clientHeight/2),behavior:'smooth'})},[playingIndex])
  useEffect(()=>{setDraftText(visibleCues.map(c=>c.text).join('\n'))},[visibleCues])
  useEffect(()=>{const rows=document.querySelectorAll<HTMLElement>('.nearby-segments .segment');rows.forEach((row,index)=>{const segment=visibleWindow.items[index],parsed=segment&&cues.some(cue=>cue.end>segment.start&&cue.start<segment.end);row.classList.toggle('has-transcript',Boolean(parsed));if(parsed)row.title='该片段已有解析原文';else row.removeAttribute('title')})},[cues,visibleWindow])
  const restoreProject=async(saved:StoredProject)=>{mediaRef.current?.pause();if(mediaUrl)URL.revokeObjectURL(mediaUrl);const file=new File([saved.media],saved.fileName,{type:saved.fileType,lastModified:saved.lastModified});mediaFileRef.current=file;audioBufferRef.current=null;setProjectId(saved.id);setFileName(saved.fileName);setMediaIsAudio(isAudioMedia(saved.fileName,saved.fileType));setMediaUrl(URL.createObjectURL(saved.media));setDuration(saved.duration);setWaveform(saved.waveform);setSegments(saved.segments);setCues(saved.cues);setSelectedIds(saved.selectedIds);setRange(saved.range);setTime(saved.range[0]);setDetectedLanguage(saved.detectedLanguage);const context=new AudioContext();audioBufferRef.current=await context.decodeAudioData((await saved.media.arrayBuffer()).slice(0));await context.close()}
  const openLibraryProject=async(id:string)=>{setRestoring(true);try{const saved=await getProject(id);if(!saved)throw new Error('missing');await restoreProject(saved);setLibraryOpen(false);setToast(`已从学习库打开 ${saved.fileName}`)}catch{setToast('项目加载失败，媒体数据可能已被浏览器清理')}finally{setRestoring(false)}}
  const deleteLibraryProject=async(id:string)=>{const item=projects.find(project=>project.id===id);if(!window.confirm(`确定删除“${item?.fileName??'这条学习记录'}”吗？保存的媒体、片段和原文都会从本机学习库删除。`))return;try{await deleteProject(id);setProjects(await listProjects());if(id===projectId)reset();setToast('学习记录已删除')}catch{setToast('学习记录删除失败')}}
  const reparseLibraryProject=async(id:string)=>{const saved=await getProject(id);if(!saved)return setToast('找不到这条学习记录');if(!window.confirm(`将使用当前的“${splitMode==='nvidia'?'高级模型':splitMode==='whisperx'?'自然语言':'静音切分'}”重新解析“${saved.fileName}”。现有片段和原文会被覆盖，是否继续？`))return;const file=new File([saved.media],saved.fileName,{type:saved.fileType,lastModified:saved.lastModified});setLibraryOpen(false);await importMedia(file)}
  const seek=(v:number)=>{setTime(v);if(mediaRef.current)mediaRef.current.currentTime=v}
  const applySelection=(ids:number[])=>{const picked=segments.filter(s=>ids.includes(s.id)).sort((a,b)=>a.start-b.start);if(!picked.length){setSelectedIds([]);setRange([0,duration||1]);return}setSelectedIds(picked.map(s=>s.id));setRange([picked[0].start,picked[picked.length-1].end]);seek(picked[0].start)}
  const toggleMulti=(s:Segment)=>{if(selectedIds.length>1&&selectedIds.includes(s.id)){applySelection([s.id]);setToast(`已收缩为仅循环片段 ${segments.findIndex(item=>item.id===s.id)+1}`);return}let ids=selectedIds.includes(s.id)?selectedIds.filter(id=>id!==s.id):[...selectedIds,s.id];if(ids.length>1){const ix=ids.map(id=>segments.findIndex(x=>x.id===id)).sort((a,b)=>a-b);ids=segments.slice(ix[0],ix[ix.length-1]+1).map(x=>x.id)}if(ids.length>5){setToast('本地原文解析最多选择 5 个连续片段');return}applySelection(ids)}
  const playFull=async()=>{if(!mediaRef.current)return setToast('请先导入音视频');setLooping(false);setSelectedIds([]);setRange([0,duration]);seek(0);await mediaRef.current.play()}
  const togglePlay=async()=>{const m=mediaRef.current;if(!m)return setToast('请先导入音视频');if(m.paused){if(time>=range[1]-.05)seek(range[0]);await m.play()}else m.pause()}
  const onTimeUpdate=()=>{const m=mediaRef.current;if(!m)return;if(looping&&m.currentTime>=range[1]){m.currentTime=range[0];void m.play()}setTime(m.currentTime)}
  const importMedia=async(file?:File)=>{
    if(!file)return
    mediaFileRef.current=file;audioBufferRef.current=null;setMediaIsAudio(isAudioMedia(file.name,file.type))
    if(mediaUrl)URL.revokeObjectURL(mediaUrl)
    setMediaUrl(URL.createObjectURL(file));setFileName(file.name);setProcessingMessage('正在浏览器中提取音轨、计算真实波形…');setProcessing(true);setSegments([]);setWaveform([]);setSelectedIds([]);setCues([]);setDetectedLanguage('');setTime(0)
    try{
      const context=new AudioContext(),buffer=await context.decodeAudioData((await file.arrayBuffer()).slice(0))
      audioBufferRef.current=buffer;setDuration(buffer.duration);setWaveform(createWaveform(buffer));await context.close()
      if(splitMode!=='silence'){
        const cloud=splitMode==='nvidia'
        setProcessingMessage(cloud?'正在准备完整音轨，随后使用高级模型解析…':'正在使用自然语言模型生成时间戳…')
        const cloudMedia=cloud?new File([encodeWavClip(buffer,0,buffer.duration)],`${file.name.replace(/\.[^.]+$/,'')}-complete.wav`,{type:'audio/wav'}):file
        const body=new FormData();body.append('media',cloudMedia);body.append('language',cloud?cloudLanguage:'auto');body.append('model',localModel);if(cloud){body.append('expected_duration',String(buffer.duration));body.append('expected_bytes',String(cloudMedia.size))}
        let statusTimer:number|undefined
        if(cloud)statusTimer=window.setInterval(()=>{void fetch(`${API_BASE}/nvidia/status`).then(r=>r.ok?r.json():null).then((status:{message?:string}|null)=>{if(status?.message)setProcessingMessage(status.message)}).catch(()=>undefined)},800)
        let response:Response
        try{response=await fetch(`${API_BASE}/segment/${cloud?'nvidia':'whisperx'}`,{method:'POST',body})}finally{if(statusTimer!==undefined)window.clearInterval(statusTimer)}
        if(!response.ok){const detail=await response.json().catch(()=>({detail:cloud?'高级模型解析失败':'自然语言解析失败'}));throw new Error(detail.detail)}
        const result=await response.json() as {segments:Segment[];cues:Cue[];language:string;device?:string;model:string;provider?:string;request_id?:string;cloud_chunks?:number;cloud_elapsed_seconds?:number;decoded_audio_seconds?:number;has_word_timestamps?:boolean}
        setSegments(result.segments);setCues(result.cues);setDetectedLanguage(result.language)
        if(result.segments[0]){setSelectedIds([result.segments[0].id]);setRange([result.segments[0].start,result.segments[0].end])}
        setToast(cloud?`高级模型解析完成：${result.segments.length} 个自然片段`:`自然语言解析完成：${result.segments.length} 个片段`)
      }else{
        setProcessingMessage('正在按静音间隔生成片段…');const found=detectSegments(buffer);setSegments(found)
        if(found[0]){setSelectedIds([1]);setRange([found[0].start,found[0].end])}
        setToast(`已读取真实音轨，并按静音切成 ${found.length} 段`)
      }
    }catch(error){setToast(error instanceof TypeError?'无法连接本地转写服务，请先启动 backend':error instanceof Error?error.message:'媒体处理失败');setRange([0,1])}finally{setProcessing(false)}
  }
  const importSubtitle=async(file?:File)=>{if(!file)return;const parsed=parseSubtitles(await file.text());setCues(parsed);setToast(parsed.length?`已导入 ${parsed.length} 条原文字幕`:'没有识别到有效的 SRT/VTT 字幕')}
  const importFromUrl=async()=>{const url=sourceUrl.trim();if(!url)return setToast('请输入视频链接');setDialog(null);setSourceUrl('');setUrlLoading(true);setProcessing(true);setProcessingMessage('正在取得网页视频，约需几十秒…');try{const response=await fetch(`${API_BASE}/import/url`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});if(!response.ok){if(response.status===404)throw new Error('当前运行的是旧版后端：请完全停止 Echo Loop 后重新启动');const body=await response.json().catch(()=>({detail:`网页视频加载失败（HTTP ${response.status}）`}));throw new Error(body.detail)}const blob=await response.blob();if(!blob.size)throw new Error('后端返回了空视频');const name=decodeURIComponent(response.headers.get('X-EchoLoop-Filename')||'imported-video.mp4');await importMedia(new File([blob],name,{type:blob.type||'video/mp4',lastModified:Date.now()}))}catch(error){setToast(error instanceof TypeError?'无法连接新版后端，请重新启动 Echo Loop':error instanceof Error?error.message:'网页视频加载失败')}finally{setUrlLoading(false);setProcessing(false)}}
  const transcribeLocal=async()=>{const file=mediaFileRef.current;if(!file)return setToast('请先导入音视频');if(selectedIds.length<1)return setToast('请先勾选 1–5 个需要解析的片段');if(selectedIds.length>5)return setToast('每次最多解析 5 个连续片段');setTranscribing(true);const selection:[number,number]=[range[0],range[1]];try{const decoded=audioBufferRef.current,isClip=Boolean(decoded),upload=isClip?new File([encodeWavClip(decoded!,selection[0],selection[1])],'selected-range.wav',{type:'audio/wav'}):file;const body=new FormData();body.append('media',upload);body.append('model',localModel);body.append('language','auto');body.append('start',String(isClip?0:selection[0]));body.append('end',String(isClip?selection[1]-selection[0]:selection[1]));const response=await fetch(`${API_BASE}/transcribe`,{method:'POST',body});if(!response.ok){const detail=await response.json().catch(()=>({detail:'转写失败'}));throw new Error(detail.detail)}const data=await response.json() as {cues:Cue[];language:string};const returned=data.cues.map(cue=>isClip?{...cue,start:cue.start+selection[0],end:cue.end+selection[0]}:cue);setCues(previous=>[...previous.filter(cue=>cue.end<=selection[0]||cue.start>=selection[1]),...returned].sort((a,b)=>a.start-b.start).map((cue,index)=>({...cue,id:index+1})));setDetectedLanguage(data.language);setToast(`局部转写完成：仅处理 ${(selection[1]-selection[0]).toFixed(1)} 秒音频`)}catch(error){setToast(error instanceof TypeError?'无法连接本地转写服务，请先启动 backend':error instanceof Error?error.message:'局部转写失败')}finally{setTranscribing(false)}}
  const move=(d:number)=>{const i=currentIndex<0?0:currentIndex,n=segments[Math.max(0,Math.min(segments.length-1,i+d))];if(n)applySelection([n.id])}
  const selectCurrent=()=>{const current=segments[playingIndex];if(!current)return setToast('请先导入并播放媒体');mediaRef.current?.pause();applySelection([current.id]);setLooping(true);setToast(`已选中片段 ${playingIndex+1}，并开启循环`)}
  const clearSelection=()=>{setSelectedIds([]);setLooping(false);setRange([0,duration||1]);setToast('已清空片段选择，恢复完整播放范围')}
  const previewLearner=()=>{if(!projectId)return setToast('请先导入并保存一个学习项目');window.open(`/learn/local?project=${encodeURIComponent(projectId)}`,'_blank','noopener,noreferrer')}
  const exportCourse=async()=>{const media=mediaFileRef.current;if(!media||!duration)return setToast('请先导入并完成课程资料');setExporting(true);setToast('正在生成离线课程包，请保持页面打开…');try{const result=await exportCoursePackage({id:projectId||projectIdFor(media),title:fileName.replace(/\.[^.]+$/,''),language:detectedLanguage,duration,media,mediaName:media.name,mediaType:media.type,cues,segments});const url=URL.createObjectURL(result.blob),link=document.createElement('a');link.href=url;link.download=result.fileName;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),30000);setToast(`课程包已导出：${(result.blob.size/1024/1024).toFixed(1)} MB`)}catch(error){setToast(error instanceof Error?`导出失败：${error.message}`:'课程包导出失败')}finally{setExporting(false)}}
  const selectCue=(cue:Cue)=>{mediaRef.current?.pause();setRange([cue.start,cue.end]);seek(cue.start);setLooping(true);setDraftText(cue.text);setToast(`已循环播放这条字幕；原有 ${selectedIds.length} 个片段保持选中`)}
  const saveRecord=()=>{if(!mediaUrl)return setToast('请先导入媒体');const text=draftText.trim();if(!text)return setToast('请先填写片段原文');setCues(previous=>[...previous.filter(cue=>cue.end<=range[0]||cue.start>=range[1]),{id:Date.now(),start:range[0],end:range[1],text,edited:true}].sort((a,b)=>a.start-b.start).map((cue,index)=>({...cue,id:index+1})));const record:SavedRecord={id:Date.now(),fileName,start:range[0],end:range[1],text,created:new Date().toLocaleString()};const next=[record,...records];setRecords(next);localStorage.setItem('echo-loop-records',JSON.stringify(next));setToast('修改后的原文已保存，并收入学习记录')}
  const requestTranscription=()=>{const target=selectedRange??range;const hasEdited=cues.some(cue=>cue.edited&&cue.end>target[0]&&cue.start<target[1]);if(hasEdited&&!window.confirm('当前选区包含人工修改过的原文。重新解析会覆盖这些修改，是否继续？'))return;void transcribeLocal()}
  const addRange=()=>{if(!duration)return setToast('请先导入媒体');const start=Math.max(0,Math.min(range[0],duration-1)),end=Math.max(start+1,Math.min(range[1],duration)),next=[...segments,{id:0,start,end}].sort((a,b)=>a.start-b.start).map((s,i)=>({...s,id:i+1}));setSegments(next);setDialog(null);setToast('已添加手动片段')}
  const toggleRecord=async()=>{if(recording&&recorderRef.current){recorderRef.current.stop();setRecording(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks:Blob[]=[];const recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{setRecordingUrl(URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType})));stream.getTracks().forEach(t=>t.stop());setToast('录音完成')};recorder.start();recorderRef.current=recorder;setRecording(true)}catch{setToast('无法使用麦克风，请检查权限')}}
  const reset=()=>{mediaRef.current?.pause();mediaFileRef.current=null;audioBufferRef.current=null;setProjectId('');setMediaUrl('');setFileName('未导入媒体');setMediaIsAudio(false);setDuration(0);setWaveform([]);setSegments([]);setSelectedIds([]);setRange([0,1]);setTime(0);setCues([]);setDraftText('');setDetectedLanguage('')}
  return <div className="app-shell">{libraryOpen&&<LibraryPanel projects={projects} onClose={()=>setLibraryOpen(false)} onOpen={id=>void openLibraryProject(id)} onDelete={id=>void deleteLibraryProject(id)} onReparse={id=>void reparseLibraryProject(id)}/>}<header><div className="brand"><span className="brand-mark"><Volume2 size={19}/></span><span>EchoLoop</span></div><nav><button className="nav-active"><Headphones size={17}/>精听室</button><button onClick={()=>setLibraryOpen(true)}><BookOpen size={17}/>学习库</button><button onClick={previewLearner}><GraduationCap size={17}/>学习端预览</button></nav><div className="header-actions"><span className={`save-state ${saveStatus}`}>{saveStatus==='saving'?'保存中…':saveStatus==='saved'?'已保存':saveStatus==='error'?'保存失败':'本地'}</span><button className="icon-button" onClick={()=>setDialog('help')}><CircleHelp size={19}/></button><button className="icon-button" onClick={()=>setDialog('settings')}><Settings2 size={19}/></button><button className="avatar" onClick={()=>setLibraryOpen(true)}>库</button></div></header><main>
    <div className="topline"><div><div className="eyebrow">{splitMode==='nvidia'?'高级模型解析':splitMode==='whisperx'?'自然语言切分':'静音切分'} · 局部原文解析</div><h1>{fileName.replace(/\.[^.]+$/,'')}</h1></div><div className="top-actions"><button className="secondary" onClick={reset}><Plus size={17}/>新建学习</button><select className="model-select" value={splitMode} onChange={e=>setSplitMode(e.target.value as 'silence'|'whisperx'|'nvidia')} title="解析模型"><option value="silence">静音切分</option><option value="whisperx">自然语言</option><option value="nvidia">高级模型</option></select><button className="secondary" disabled={transcribing||selectedIds.length<1||selectedIds.length>5} onClick={requestTranscription}><Sparkles size={17}/>{transcribing?'局部转写中…':`解析选中片段${selectedIds.length?` (${selectedIds.length})`:''}`}</button><button className="secondary" onClick={()=>subtitleRef.current?.click()}><Captions size={17}/>导入字幕</button><input ref={subtitleRef} type="file" accept=".srt,.vtt,text/vtt" hidden onChange={e=>{void importSubtitle(e.target.files?.[0]);e.target.value=''}}/><button className="secondary" disabled={exporting||!mediaUrl} onClick={()=>void exportCourse()}><Download size={17}/>{exporting?'正在打包…':'导出课程'}</button><button className="primary" onClick={()=>setDialog('import')}><Upload size={17}/>导入音视频</button><input ref={fileRef} type="file" accept="audio/*,video/*" hidden onChange={e=>{void importMedia(e.target.files?.[0]);e.target.value='';setDialog(null)}}/></div></div>
    {splitMode==='nvidia'&&<div className="cloud-trace-link"><span>调试</span><a href={`${API_BASE}/nvidia/trace`} target="_blank" rel="noreferrer">查看高级模型交互报文</a></div>}
    {captionTarget&&createPortal(<div className={`live-caption-area ${showLiveCaption?'open':''}`}><button className="live-caption-toggle" onClick={()=>setShowLiveCaption(value=>!value)}>{showLiveCaption?<EyeOff size={14}/>:<Eye size={14}/>} {showLiveCaption?'隐藏字幕':'显示字幕'}</button>{showLiveCaption&&activeCue&&<div key={activeCue.id} className={`live-caption ${playing?'playing':''}`} style={{animationDuration:`${Math.max(1,(activeCue.end-activeCue.start)/Math.max(.5,speed))}s`}}><p>{activeCue.text}</p></div>}</div>,captionTarget)}
    {mediaStageTarget&&mediaUrl&&mediaIsAudio&&createPortal(<div className="audio-media-cover"><span><FileAudio size={38}/></span><b>{fileName}</b><small>音频文件</small></div>,mediaStageTarget)}
    {subtitleActionsTarget&&createPortal(<button className="transcript-visibility" onClick={()=>setShowTranscript(value=>!value)}>{showTranscript?<EyeOff size={13}/>:<Eye size={13}/>} {showTranscript?'隐藏原文':'显示原文'}</button>,subtitleActionsTarget)}
    {segmentToolsTarget&&selectedIds.length>0&&createPortal(<button className="clear-selection" onClick={clearSelection}><X size={12}/>清空</button>,segmentToolsTarget)}
    {processing&&<div className="processing"><Waves size={18}/><span>{processingMessage}</span><i/></div>}
    <section className="workspace"><aside className="segments-panel"><div className="panel-head"><div><b>附近片段</b><span>{playingIndex>=0?`当前 ${playingIndex+1} · `:''}{segments.length?`${visibleWindow.start+1}–${visibleWindow.end} / 共 ${segments.length} 段`:'0 段'}</span></div><button className="icon-button" onClick={()=>setDialog('range')}><MoreHorizontal size={19}/></button></div><div className="segment-tools"><button onClick={()=>void playFull()}><Play size={13}/>完整播放</button><button className="locate-current" onClick={selectCurrent}><LocateFixed size={13}/>选中当前 {playingIndex>=0?playingIndex+1:''}</button></div><div className="segments nearby-segments">{segments.length?visibleWindow.items.map((s,offset)=>{const i=visibleWindow.start+offset;return <button ref={i===playingIndex?currentSegmentRef:null} className={`segment ${selectedIds.includes(s.id)?'selected':''} ${i===playingIndex?'now-playing':''}`} key={s.id} onClick={()=>applySelection([s.id])}><input type="checkbox" checked={selectedIds.includes(s.id)} onChange={()=>toggleMulti(s)} onClick={e=>e.stopPropagation()}/><span className="segment-num">{String(i+1).padStart(2,'0')}</span><span className="segment-copy"><span className="speaker">{i===playingIndex?'● 正在播放':'静音检测片段'}</span><span className="segment-text">片段 {String(i+1).padStart(2,'0')}</span><span className="segment-time">{fmt(s.start,true)} — {fmt(s.end,true)} · {(s.end-s.start).toFixed(1)} 秒</span></span></button>}):<div className="empty-segments"><Scissors size={25}/><span>导入后按静音间隔自动切分</span></div>}</div><button className="add-segment" onClick={()=>setDialog('range')}><Plus size={15}/>手动添加片段</button></aside>
      <div className="study-area"><div className="media-card"><div className={`media-stage ${mediaUrl?'has-media':''}`}>{mediaUrl?<video ref={mediaRef} src={mediaUrl} onLoadedMetadata={e=>{const d=e.currentTarget.duration;if(Number.isFinite(d)&&!duration){setDuration(d);setRange([0,d])}}} onTimeUpdate={onTimeUpdate} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/>:<button className="media-placeholder" onClick={()=>fileRef.current?.click()}><FileAudio size={33}/><span>导入音频或视频</span><small>文件仅在本机处理</small></button>}<div className="timecode">{fmt(time)} / {fmt(duration)}</div></div><div className="wave-wrap"><div className="range-label" style={{left:`${duration?range[0]/duration*100:0}%`,width:`${duration?(range[1]-range[0])/duration*100:0}%`}}><span>{Math.max(0,range[1]-range[0]).toFixed(1)} 秒</span></div><div className="waveform real-wave">{(waveform.length?waveform:Array(100).fill(3)).map((h,i)=>{const at=i/(waveform.length||100)*duration;return <i key={i} className={at>=range[0]&&at<=range[1]?'in-range':''} style={{height:h}}/>})}</div><input className="scrubber visible-scrubber" type="range" min="0" max={duration||1} step="0.05" value={time} onChange={e=>seek(+e.target.value)}/></div><div className="controls"><button className={looping?'control active':'control'} onClick={()=>setLooping(v=>!v)} title="区间循环"><Repeat2 size={19}/></button><button className="control" onClick={()=>move(-1)}><ChevronLeft size={24}/></button><button className="play-button" onClick={()=>void togglePlay()}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button className="control" onClick={()=>move(1)}><ChevronRight size={24}/></button><button className="speed" onClick={()=>setSpeed(speed>=1.5?.5:+(speed+.25).toFixed(2))}>{speed}×</button><div className="control-spacer"/><button className="control" onClick={()=>seek(range[0])}><RotateCcw size={18}/></button><button className={muted?'control active':'control'} onClick={()=>{setMuted(v=>!v);if(mediaRef.current)mediaRef.current.muted=!muted}}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></div>
        <div className="practice-card"><div className="practice-tabs"><button className={mode==='listening'?'active':''} onClick={()=>setMode('listening')}>原文字幕</button><button className={mode==='shadowing'?'active':''} onClick={()=>setMode('shadowing')}>复述练习</button></div><div className="selection-summary compact"><span className="summary-icon"><Captions size={19}/></span><small>{selectedIds.length>1?`已选 ${selectedIds.length} 个连续片段`:'当前复听范围'}</small><h2>{fmt(range[0],true)} — {fmt(range[1],true)}</h2><p>{(range[1]-range[0]).toFixed(1)} 秒</p></div>{mode==='listening'?<><div className="subtitle-head"><b>对应原文</b><button onClick={()=>subtitleRef.current?.click()}><Upload size={13}/>{cues.length?'更换字幕':'导入 SRT / VTT'}</button></div><div className="cue-list">{visibleCues.length?visibleCues.map(cue=><button key={cue.id} className="cue" onClick={()=>selectCue(cue)}><span>{fmt(cue.start,true)}</span><p>{cue.text}</p><Play size={13}/></button>):<div className="cue-empty"><Captions size={22}/><span>{cues.length?'当前范围没有对应字幕':'导入现有字幕文件，或在下方手动填写原文'}</span></div>}</div><label className="transcript-editor">片段原文<textarea value={draftText} onChange={e=>setDraftText(e.target.value)} placeholder="输入或修订当前片段的原文…"/></label><button className="save-record" onClick={saveRecord}><BookmarkPlus size={17}/>将片段和原文收入记录</button></>:<><div className="local-note"><b>复述与比较</b><p>先循环听熟当前范围，再脱离原音进行复述。录音会保留在当前会话中，保存片段后可供后续 AI 比较和纠正。</p></div><div className="coach-row"><button className="hint-button" onClick={()=>setDialog('range')}><Scissors size={18}/>调整时间段</button><button className={`record-button ${recording?'recording':''}`} onClick={()=>void toggleRecord()}><Mic2 size={18}/>{recording?'结束录音':'开始复述'}</button></div>{recordingUrl&&<div className="recording-playback"><span>我的复述</span><audio controls src={recordingUrl}/></div>}<button className="save-record" onClick={saveRecord}><BookmarkPlus size={17}/>保存本次练习</button></>}</div></div></section>
  </main>{toast&&<div className="toast">{toast}</div>}{dialog&&<div className="modal-backdrop" onMouseDown={()=>!urlLoading&&setDialog(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" disabled={urlLoading} onClick={()=>setDialog(null)}><X size={18}/></button>{dialog==='import'&&<><h2>导入音视频</h2><p className="import-lead">粘贴 TBS NewsDig 或 YouTube 单个视频链接，也可以从本机选择媒体文件。</p><form className="url-import" onSubmit={e=>{e.preventDefault();void importFromUrl()}}><label>网页链接<input autoFocus type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="粘贴 TBS NewsDig / YouTube 视频 URL" disabled={urlLoading||processing}/></label><button className="primary" type="submit" disabled={urlLoading||processing||!sourceUrl.trim()}>{urlLoading?'正在加载视频…':'加载、解析、学习'}</button><small>支持 YouTube 普通视频、Shorts、Live 回放和 youtu.be 短链接；仅用于你有权使用的内容。</small></form><div className="import-divider"><span>或</span></div><button className="secondary local-import" onClick={()=>fileRef.current?.click()} disabled={urlLoading}><FileAudio size={17}/>从本机选择音视频</button></>}{dialog==='help'&&<><h2>本地精听流程</h2><ol><li>导入媒体和已有的 SRT/VTT 字幕。</li><li>勾选相邻片段组成复听范围。</li><li>点击右侧某条字幕可精确循环该句。</li><li>修订原文后收入记录，用于复述和后续比较。</li></ol></>}{dialog==='settings'&&<><h2>播放设置</h2><label className="field">默认速度<select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value="0.5">0.5×</option><option value="0.75">0.75×</option><option value="1">1.0×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select></label></>}{dialog==='history'&&<><h2>学习记录</h2><div className="saved-list">{records.length?records.map(record=><button key={record.id} onClick={()=>{setRange([record.start,record.end]);setDraftText(record.text);seek(record.start);setLooping(true);setDialog(null)}}><b>{record.fileName}</b><span>{fmt(record.start,true)} — {fmt(record.end,true)} · {record.created}</span><p>{record.text||'未填写原文'}</p></button>):<p>还没有收藏片段。</p>}</div><p className="modal-note">文字和时间范围已保存在本机浏览器；重播时需要重新导入原媒体文件。</p></>}{dialog==='range'&&<><h2>手动添加片段</h2><p>输入开始与结束时间，最短 1 秒。</p><div className="range-fields"><label className="field">开始（秒）<input type="number" min="0" max={Math.max(0,duration-1)} step="0.1" value={range[0]} onChange={e=>setRange([Math.max(0,+e.target.value),range[1]])}/></label><label className="field">结束（秒）<input type="number" min={range[0]+1} max={duration} step="0.1" value={range[1]} onChange={e=>setRange([range[0],Math.max(range[0]+1,+e.target.value)])}/></label></div><button className="primary modal-action" onClick={addRange}><Plus size={16}/>添加片段</button></>}</div></div>}</div>
}
